### ISSUE TITLE
Mention on docs: ports used by videobridge (TCP/443, TCP/4443, UDP 10000-20000) has to allow inbound traffic

### ISSUE THREAD

**Issue by cho-is** [freedomofpress/ansible-role-jitsi-meet#22]

**Comment by conorsch** [comment]
@cho-is Fair point, the docs could be more explicit about the firewall settings. The role does automatically open up those ports via `ufw`, though. (Set `jitsi_meet_configure_firewall: false` to disable.) Was the automatic host-based firewall config not working for you? If so, I'd like to address those concerns as well as update the README.

**Comment by cho-is** [comment]
Your Ansible script is great, tested on AWS EC2 latest Ubuntu machine. 
I found which port needed to open on a jitsi-meet issue.

The Security Group needs these inbound tags.

**Comment by conorsch** [comment]
Perfect, thanks for the explanation—I'll make sure to target the docs update appropriately. Glad to hear you're enjoying the role! Jitsi Meet is a great piece of software.
