### ISSUE TITLE
Possible nginx changes?

### ISSUE THREAD

**Issue by ageis** [freedomofpress/ansible-role-jitsi-meet#26]
This task failed for me, as nginx was not installed via the jitsi-meet package for some reason

```
TASK [ansible-role-jitsi-meet : Copy Nginx config for Jitsi Meet domain.] ******
fatal: [meet]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /etc/nginx/sites-available does not exist"}
```

Not sure why, as it is listed in depends.

```
root@meet:~# apt-cache depends jitsi-meet
jitsi-meet
 |Depends: debconf
  Depends: <debconf-2.0>
    cdebconf
    debconf
  Depends: jitsi-videobridge
  Depends: jitsi-meet-prosody
 |Depends: openjdk-8-jre-headless
  Depends: nginx
    nginx-extras
    nginx-light
    nginx-full
```

Installed it manually to get the task to succeed, but found that jitsi-videobridge was already bound to port 443.

```
Oct 16 00:52:40 meet nginx[18518]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
root@meet:~# netstat -tulpn | grep 443
tcp6       0      0 :::443                  :::*                    LISTEN      16284/java      
root@meet:~# ps aux | grep 16284
jvb      16284  1.2 11.1 4062392 56556 ?       Sl   00:46   0:04 java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError
```

Got nginx running by killing that, now jvb is only bound to UDP 10000+23347. Things seem to work, so I haven't done any further digging on what changed or why this occurred. There is this though:

```
/etc/jitsi/videobridge/sip-communicator.properties:2:org.jitsi.videobridge.rest.jetty.port=443
/etc/jitsi/videobridge/sip-communicator.properties:11:org.jitsi.videobridge.rest.jetty.tls.port=443
/etc/jitsi/videobridge/sip-communicator.properties:12:org.jitsi.videobridge.TCP_HARVESTER_PORT=443
```

**Comment by msheiny** [comment]
Hey @ageis - what version of `jitsi-meet` does your box report? I noticed we are on an unstable branch - Been debating if we should jump onto the stable repo. 

Also we've been utilizing the (jdauphant/ansible-role-nginx)[https://github.com/jdauphant/ansible-role-nginx] everywhere for nginx config. If we are experiencing any nginx issues on recent packages here, I do think this presents a good excuse to add that role as a galaxy dependency and rip out the custom nginx logic we have here.

**Comment by conorsch** [comment]
> I noticed we are on an unstable branch - Been debating if we should jump onto the stable repo. 

Had a feature branch lying around that implemented stable repos, that's in #27 now.

**Comment by ageis** [comment]
@msheiny I am now on stable 1.0.1338-1.

I will mention that something weird happened a week ago and the config.js got totally wiped out. Must have been unattended upgrades of the unstable package? I dunno... Like I said, haven't had a chance to dig deep. But I do think the whole role should be re-tested cause I suspect there might be breaking changes happening upstream.

**Comment by conorsch** [comment]
> I will mention that something weird happened a week ago and the config.js got totally wiped out.

Anecdotal, but I also observed this on a personal meet machine a few weeks ago—also running unstable. Will move that box to stable branch once #27 lands and monitor over time.

**Comment by conorsch** [comment]
No problems since switching from unstable to stable repo. Chalking this up to "unstable repo is unstable."
